---
- hosts: all
  sudo: yes
  tasks:
    - pip: name={{ item.name }} version={{ item.version }}
      with_items:
        - {name: 'virtualenv', version: 13.0.3}
        - {name: 'virtualenvwrapper', version: 4.6.0}
        - {name: 'gunicorn', version: 19.3.0}
        - {name: 'supervisor', version: 3.1.3}

    - copy: src=files/nginx/default.conf dest=/etc/nginx/sites-available/default
    - copy: src={{ item }} dest=/etc/
      with_items:
        - files/gunicorn/gunicorn.conf.py
        - files/supervisord.conf

    - lineinfile: dest=/home/vagrant/.bashrc line="{{ item }}"
      with_items:
        - "export WORKON_HOME=$HOME/.virtualenvs"
        - "export PROJECT_HOME=$HOME/Devel"
        - "source /usr/local/bin/virtualenvwrapper.sh"
        - "workon default"
      sudo: no

    - shell: |
        source /home/vagrant/.bashrc
        source /usr/local/bin/virtualenvwrapper.sh
        mkvirtualenv -p /usr/bin/python3 default
        workon default
        pip install django
        cd /vagrant
        django-admin startproject mysite
        sudo supervisord -c /etc/supervisord.conf
      args:
        executable: /bin/bash
      sudo: no
      notify: restart_nginx

    - service: name=nginx state=running enabled=yes

  handlers:
    - name: restart_nginx
      service: name=nginx state=restarted
