---
- hosts: all
  sudo: yes
  tasks:
    - name: Nginxをインストール
      apt: name={{ item }} state=present install_recommends=no cache_valid_time=3600 update_cache=yes
      with_items:
        - nginx

    - name: Virtualenv,Gunicorn,Supervisorをインストール
      pip: name={{ item.name }} version={{ item.version }}
      with_items:
        - {name: 'virtualenv', version: 12.0.7}
        - {name: 'virtualenvwrapper', version: 4.3.2}
        - {name: 'gunicorn', version: 19.2.1}
        - {name: 'supervisor', version: 3.1.3}
      
    - name: Nginxのサービスを有効化
      service: name=nginx state=running enabled=yes
      
    - name: Nginxの設定を変更
      copy: src=files/nginx/default.conf dest=/etc/nginx/sites-available/default

    - name: Gunicornの設定を転送
      copy: src=files/gunicorn/gunicorn.conf.py dest=/etc/
    
    - name: Supervisorの設定を転送
      copy: src=files/supervisord.conf dest=/etc/

    - lineinfile: dest=/home/vagrant/.bashrc line="{{ item }}"
      with_items:
        - "export WORKON_HOME=$HOME/.virtualenvs"
        - "export PROJECT_HOME=$HOME/Devel"
        - "source /usr/local/bin/virtualenvwrapper.sh"
      sudo: no
      
    - shell: executable=/bin/bash source /home/vagrant/.bashrc; source /usr/local/bin/virtualenvwrapper.sh; mkvirtualenv -p /usr/bin/python3 default; workon default; cd /home/vagrant; pip install django; django-admin startproject mysite
      sudo: no

    - shell: supervisord -c /etc/supervisord.conf
      notify: restart_nginx
      
  handlers:
    - name: restart_nginx
      service: name=nginx state=restarted